src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $status;

    /**
     * @ORM\OneToMany(targetEntity=ProductCharacteristics::class, mappedBy="product")
     */
    private $ProductCharacteristics;

    /**
     * @ORM\OneToMany(targetEntity=Budget::class, mappedBy="product")
     */
    private $budget;

    public function __construct()
    {
        $this->ProductCharacteristics = new ArrayCollection();
        $this->budget = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(?bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection|ProductCharacteristics[]
     */
    public function getProductCharacteristics(): Collection
    {
        return $this->ProductCharacteristics;
    }

    public function addProductCharacteristic(ProductCharacteristics $productCharacteristic): self
    {
        if (!$this->ProductCharacteristics->contains($productCharacteristic)) {
            $this->ProductCharacteristics[] = $productCharacteristic;
            $productCharacteristic->setProduct($this);
        }

        return $this;
    }

    public function removeProductCharacteristic(ProductCharacteristics $productCharacteristic): self
    {
        if ($this->ProductCharacteristics->removeElement($productCharacteristic)) {
            // set the owning side to null (unless already changed)
            if ($productCharacteristic->getProduct() === $this) {
                $productCharacteristic->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Budget[]
     */
    public function getBudget(): Collection
    {
        return $this->budget;
    }

    public function addBudget(Budget $budget): self
    {
        if (!$this->budget->contains($budget)) {
            $this->budget[] = $budget;
            $budget->setProduct($this);
        }

        return $this;
    }

    public function removeBudget(Budget $budget): self
    {
        if ($this->budget->removeElement($budget)) {
            // set the owning side to null (unless already changed)
            if ($budget->getProduct() === $this) {
                $budget->setProduct(null);
            }
        }

        return $this;
    }

}

src/Controller/Front/BudgetController.php
<?php

namespace App\Controller\Front;

use DateTime;
use App\Entity\User;
use App\Entity\Budget;
use App\Entity\Product;
use App\Event\BudgetRequestEvent;
use App\Service\EmailManagerService;
use App\Service\BudgetManagerService;
use App\Entity\ProductCharacteristics;
use App\EventSubscriber\MailerSubscriber;
use Symfony\Component\BrowserKit\Response;
use Symfony\Contracts\EventDispatcher\Event;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\EventDispatcher\EventDispatcher;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class BudgetController extends AbstractController
{

    /**
     * @Route("/{_locale}/budget", name="budget", requirements={"_locale": "es|en"}, defaults={"_locale": "es"}, methods={"GET"})
     */
    public function index()
    {
        $products = $this->getDoctrine()->getRepository(Product::class)->findAll();
        return $this->render('front/budget.html.twig', ['products' => $products]);
    }

    /**
     * @Route("/{_locale}/budget_summary", name="budget_summary", requirements={"_locale": "es|en"}, defaults={"_locale": "es"}, methods={"GET"})
     */
    public function bugetSummary(BudgetManagerService $budgetManagerService, SessionInterface $session)
    {

        $idBudget = $session->get('id-budget');
        $budget = $this->getDoctrine()->getRepository(Budget::class)->findOneBy(['id' => $idBudget]);
        $totalPrice = $budgetManagerService->calculateTotalPrice($budget);

        return $this->render('front/budget-summary.html.twig', [
            'budget' => $budget,
            'totalPrice' => $totalPrice
        ]);
    }

    /**
     * @Route("/form_budget", name="form_budget", methods={"POST"})
     */
    public function proccessFormBudget(
        Request $request,
        UserPasswordEncoderInterface $passwordEncoder,
        MailerSubscriber $mailerSubscriber,
        EmailManagerService $emailManagerService,
        SessionInterface $session
    ) {

        $em = $this->getDoctrine()->getManager();

        /* Get data */
        $productId = $request->request->get('product');
        $userName = $request->request->get('user-name');
        $userEmail = $request->request->get('user-email');
        $userPhone = $request->request->get('user-phone');
        $characteristics = $request->request->get('characteristics');
        $token = str_shuffle("abcdefghijklmnopqrstuvwxyz0123456789" . uniqid());

        $user = new User();
        $user->setName($userName);
        $user->setEmail($userEmail);
        $user->setPhone($userPhone);
        $user->setRoles([User::CUSTOMER]);
        $user->setCreatedAt(new DateTime());
        $user->setUpdatedAt(new DateTime());
        $user->setPassword($passwordEncoder->encodePassword($user, $token));
        $user->setAccessToken($token);
        $em->persist($user);

        $characteristics = $em->getRepository(ProductCharacteristics::class)->findBy(['id' => $characteristics]);
        $product = $em->getRepository(Product::class)->findOneBy(['id' => $productId]);

        // $dispatcher = new EventDispatcher();
        // $dispatcher->addSubscriber($mailerSubscriber);
        // $budget = new BudgetRequestEvent($user);
        // $dispatcher->dispatch($budget,  BudgetRequestEvent::EVENT_NAME);

        $budget = new Budget();
        $budget->setUser($user);
        $budget->setProduct($product);
        foreach ($characteristics as $characteristic) {
            $budget->addProductCharacteristic($characteristic);
        }
        $em->persist($budget);
        $em->flush();

        $session->set('id-budget', $budget->getId());
        $emailManagerService->toCustomerAccessBackend($budget);

        return $this->redirectToRoute('budget_summary');
    }
}

src/Controller/Front/IndexController.php
<?php

namespace App\Controller\Front;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class IndexController extends AbstractController
{
    /**
     * @Route("/{_locale}", name="landing", requirements={"_locale": "es|en"}, defaults={"_locale": "es"}, methods={"GET"})
     */
    public function index()
    {
        return $this->render('front/index.html.twig', [

        ]);
    }
}

templates/front/base-front.html.twig
<!DOCTYPE html>
<html>

    <head>
        <meta charset="UTF-8">
        <title>
            {% block title %}Welcome!
            {% endblock %}
        </title>
        {% block stylesheets %}
            {{ encore_entry_link_tags('front', null, 'front') }}
            {{ encore_entry_link_tags('common', null, 'common') }}
        {% endblock %}
    </head>

    <body>

        {% include "common/header.html.twig" %}

        <main class="py-1"> {% block body %}{% endblock %}
            </main>

            {% include "common/footer.html.twig" %}

            {% block javascripts %}
                {{ encore_entry_script_tags('front',null,'front') }}
            {% endblock %}

        </body>

    </html>
</body>
</html>

templates/front/budget-summary.html.twig
{% extends 'front/base-front.html.twig' %}
{% trans_default_domain 'messages' %}

{% block title %}
    {{'landing.front.budgetsummary.titleweb'|trans}}
{% endblock %}

{% block body %}

    <div class="container">
        <div class="row py-3">
            <div class="col-12">
                <h2 class="text-center">{{'landing.front.budgetsummary.titlesection'|trans}}</h2>
            </div>
        </div>

        <div class="row">
            <div class="col-8 mx-auto">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">{{'landing.front.budgetsummary.name'|trans}}</th>
                            <th scope="col">{{'landing.front.budgetsummary.description'|trans}}</th>
                            <th scope="col">{{'landing.front.budgetsummary.price'|trans}}</th>
                        </tr>
                    </thead>

                    <tbody>

                        <tr>
                            <th>{{budget.product.name}}</th>
                            <th>{{budget.product.description}}</th>
                            <th>{{budget.product.price}}</th>
                        </tr>

                        {% for productCharacteristic in budget.productCharacteristics %}
                            <tr>
                                <td>{{productCharacteristic.name}}</td>
                                <td>{{productCharacteristic.description}}</td>
                                <td>{{productCharacteristic.price}}</td>
                            </tr>
                        {% endfor %}

                        <tr>
                            <td colspan="2">Total</td>
                            <td>{{totalPrice}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>


{% endblock %}

templates/front/budget.html.twig
{% extends 'front/base-front.html.twig' %}
{% trans_default_domain 'messages' %}

{% block title %}
    {{'landing.front.budget.titleweb'|trans}}
{% endblock %}

{% block body %}

    <div class="container">
        <div class="row py-3">
            <div class="col-12">
                <h2 class="text-center">{{'landing.front.budget.titlesection'|trans}}</h2>
            </div>
        </div>

        <form action="{{path('form_budget')}}" method="post">
            {% for product in products %}
                <div class="row py-3">
                    <div class="col-6">
                        <div class="form-check">
                            <input class="form-check-input product" type="radio" name="product" id="product-{{product.id}}" value="{{product.id}}">
                            <label class="form-check-label" for="product-{{product.id}}">{{product.name}}</label>
                        </div>
                    </div>
                    <div class="col-6 characteristics" data-characteristics="product-{{product.id}}">
                        {% for characteristics in product.ProductCharacteristics %}
                            <div class="form-check" data-productid="product-{{product.id}}">
                                <input class="form-check-input checkboxes" type="checkbox" name="characteristics[]" value="{{characteristics.id}}" id="characteristics-{{characteristics.id}}">
                                <label class="form-check-label" for="characteristics-{{characteristics.id}}">
                                    {{characteristics.name}}
                                </label>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}

            <div class="row mt-3">
                <div class="col-12">
                    <h2 class="text-center">Datos del usuario</h2>
                </div>
                <div class="col-8 mx-auto">
                    <div class="form-group">
                        <label for="user-name">Name</label>
                        <input type="text" name="user-name" class="form-control" id="user-name" required>
                    </div>
                    <div class="form-group">
                        <label for="user-email">Email</label>
                        <input type="email" name="user-email" class="form-control" id="user-email" required>
                    </div>
                    <div class="form-group">
                        <label for="user-phone">Telefono
                            <label>
                                <input type="number" name="user-phone" class="form-control" id="user-phone" required>
                            </div>

                        </div>
                    </div>

                    <div class="row py-3">
                        <div class="col-12 text-center my-5">
                            <button type="submit" class="btn btn-primary btn-lg" role="button">{{'landing.front.budget.button'|trans}}</button>
                        </div>
                    </div>
                </form>
            </div>

        {% endblock %}

templates/front/index.html.twig
{% extends 'front/base-front.html.twig' %}
{% trans_default_domain 'messages' %}

{% block title %}
    {{'landing.front.body.titleweb'|trans}}
{% endblock %}

{% block body %}

    <div class="container">
        <div class="row py-2">
            <div class="col">
                <h1 class="text-center">{{'landing.front.body.title'|trans}}</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-6">
                <img src="{{asset('img/banner.jpg')}}" alt="banner" class="img-fluid">
            </div>
            <div class="col-12 col-md-6 d-flex align-items-center ">
                <h3>{{'landing.front.body.description'|trans}}</h3>
            </div>
        </div>

        <div class="row py-3">
            <div class="col-12">
                <h2 class="text-center">{{'landing.front.body.titlesection'|trans}}</h2>
            </div>
            <div class="col-12 text-center my-5">
                <a href="{{path('budget')}}" class="btn btn-primary btn-lg"  role="button">{{'landing.front.body.button'|trans}}</a>
            </div>
        </div>
    </div>

{% endblock %}